# Generated by Django 6.0.5 on 2026-05-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_custom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
