# Generated by Django 6.0.5 on 2026-05-14 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.CharField(choices=[('sachet', 'Sachet'), ('bottle', 'Bottle'), ('bag', 'Bag'), ('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('tin', 'Tin'), ('crate', 'Crate'), ('pack', 'Pack'), ('piece', 'Piece'), ('bunch', 'Bunch'), ('tuber', 'Tuber'), ('other', 'Other')], max_length=50)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
